### PR TITLE
add mock key

### PR DESCRIPTION
**Pull request by naxingyu**

### CODE REVIEW

**Review by dophist — CHANGES_REQUESTED** [review]
@naxingyu this "mock" function is producing invalid resources, even for Kaldi ("duplicated keys"), maybe the right thing to do is to change the text processing tool after TN.

**Comment by naxingyu** [comment]
That's why I call it mock, and `--has_key` and `--mock_key` won't function simultaneously. The text with mocked key won't be checked by Kaldi data utils.

**Comment by dophist** [comment]
I mean the better thing to do is to enhance kaldi's text processing tools with option like "--has_key", for now kaldi's tool can only process transcription(with key) instead of pure text, this enhancement sounds more natural than adding invalid duplicated key in TN tool.

**Comment by naxingyu** [comment]
fair enough. This is too kaldi dependent. I'll just drop.

**Pull request closed without merging**
